# Generated by Django 5.1.3 on 2024-12-31 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='servises',
            new_name='services',
        ),
    ]
