# Generated by Django 5.1.3 on 2024-12-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='description',
            field=models.CharField(default=1, max_length=3000),
        ),
    ]
