# Generated by Django 5.1.3 on 2025-01-09 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctorname', models.CharField(max_length=60)),
                ('Age', models.IntegerField()),
                ('Phone', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=30)),
                ('Place', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('DateTime', models.DateTimeField()),
                ('Patientname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
