# Generated by Django 5.1.3 on 2025-01-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='booking',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
