# Generated by Django 5.1.3 on 2025-01-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_booking_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Gender',
        ),
    ]
