# Generated by Django 5.1.3 on 2025-01-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_remove_booking_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown/Prefer Not to Say')], max_length=1, null=True),
        ),
    ]
