# Generated by Django 5.1.3 on 2025-01-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_booking_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Doctorname',
        ),
    ]
