# Generated by Django 5.1.3 on 2025-01-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_remove_booking_doctorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Doctorname',
            field=models.CharField(blank=True, choices=[('Dr . Anna Joseph', 'Dr . Anna Joseph'), ('Dr . Mahadhev', 'Dr . Mahadhev'), ('Dr . Supritha', 'Dr . Supritha'), ('Dr . Mruthula', 'Dr . Mruthula'), ('Dr . Shihab', 'Dr . Shihab'), ('Dr . Rajesh', 'Dr . Rajesh'), ('Dr . Jamsheer', 'Dr . Jamsheer'), ('Dr . Kumar', 'Dr . Kumar'), ('Dr . Meenakshi', 'Dr . Meenakshi'), ('Dr . Kavi', 'Dr . Kavi'), ('Dr . Baburaj', 'Dr . Baburaj'), ('Dr . Lakshmi', 'Dr . Lakshmi'), ('Dr . Maya', 'Dr . Maya'), ('Dr . Favas', 'Dr . Favas'), ('Dr . Rishad', 'Dr . Rishad'), ('Dr . Biju Lal', 'Dr . Biju Lal'), ('Dr . kishor kumar', 'Dr . kishor kumar'), ('Dr . Jose Antony', 'Dr . Jose Antony'), ('Dr . Sunaina', 'Dr . Sunaina'), ('Dr . Subash', 'Dr . Subash'), ('Dr . Kiran', 'Dr . Kiran'), ('Dr . Ramadas', 'Dr . Ramadas'), ('Dr . Kavitha', 'Dr . Kavitha'), ('Dr . Ravi kumar', 'Dr . Ravi kumar'), ('Dr . Anupama', 'Dr . Anupama'), ('Dr . Riya subash', 'Dr . Riya subash'), ('Dr . Jayapal Jose', 'Dr . Jayapal Jose'), ('Dr . Gogul', 'Dr . Gogul'), ('Dr . veena', 'Dr . veena'), ('Dr . Rahul Sharma', 'Dr . Rahul Sharma')], max_length=100, null=True),
        ),
    ]
