# Generated by Django 5.1.3 on 2025-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_booking_doctorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time_period',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2, null=True),
        ),
    ]
