# Generated by Django 5.1.3 on 2025-01-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_booking_time_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_period',
        ),
    ]
