# Generated by Django 5.1.3 on 2025-01-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_booking_am_pm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Time',
        ),
    ]
