# Generated by Django 5.1.3 on 2025-01-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_remove_booking_date_remove_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
