# Generated by Django 5.1.3 on 2025-01-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0020_remove_booking_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('U', 'Unknown/Prefer Not to Say')], max_length=6, null=True),
        ),
    ]
