# Generated by Django 5.1.3 on 2025-07-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0021_booking_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='AM_PM',
        ),
    ]
